name: Pull request checks

on:
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4

      - name: Run tests
        run: |
          python -m doctest -o IGNORE_EXCEPTION_DETAIL -f tests/tests.txt
